# Generated by Django 4.0.2 on 2022-02-10 22:10

from django.db import migrations, models
import django.db.models.deletion
import sampleapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=40, unique=True)),
                ('min_age', models.IntegerField(max_length=40)),
                ('max_age', models.IntegerField(max_length=40)),
                ('max_student', models.IntegerField(max_length=40)),
                ('class_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=40)),
                ('student_dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('student_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, verbose_name='Gender')),
                ('guardian_name', models.CharField(max_length=40)),
                ('contact_no', models.CharField(max_length=20, unique=True, validators=[sampleapp.models.validate_mobileno], verbose_name='Contact Number')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=40)),
                ('contact_no', models.CharField(max_length=20, unique=True, validators=[sampleapp.models.validate_mobileno], verbose_name='Contact Number')),
                ('qualifications', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Teachers_Bridge',
            fields=[
                ('ct_bridgeid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('classname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_bridge', to='sampleapp.classes')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_bridge', to='sampleapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Student_Bridge',
            fields=[
                ('cs_bridgeid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('classname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_student_bridge', to='sampleapp.classes')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_student_bridge', to='sampleapp.student')),
            ],
        ),
    ]
