# Generated by Django 4.0.2 on 2022-03-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_student_student_class_student_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('quali_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=40)),
                ('quali_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='years_exeperience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='qualifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='sampleapp.qualification'),
        ),
    ]
