# Generated by Django 4.0.2 on 2022-03-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_rename_years_exeperience_teachers_years_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='quali_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Teacher_Qualification_Bridge',
            fields=[
                ('tq_bridgeid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_qualification_bridge', to='sampleapp.qualification')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_qualification_bridge', to='sampleapp.teachers')),
            ],
        ),
    ]
